name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Pull Docker Image
        run: docker pull jasonnho/devops-pso:latest

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key-pair-devopspso.pem
          chmod 400 key-pair-devopspso.pem
          ssh -o StrictHostKeyChecking=no -i key-pair-devopspso.pem ubuntu@${{ secrets.EC2_INSTANCE_PUBLIC_DNS }} << 'EOF'
            docker pull jasonnho/devops-pso:latest
            docker rm -f devops-pso-container || true
            docker run -d -p 3000:3000 --name devops-pso-container jasonnho/devops-pso:latest
          EOF
