name: Initial configuration
on:
  push:
    branches:
      - dockerfileDebug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t jasonnho/devops-pso .

      - name: Login to docker hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Publish image to docker hub
        run: docker push jasonnho/devops-pso:latest

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull image from docker hub
        run: docker pull jasonnho/devops-pso:latest
      - name: Run vitest testing
        run: |
          docker run --rm jasonnho/devops-pso:latest sh -c "npm install && npm test"
