name: Initial configuration
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v3
      - name: Set environment
        run: npm install
      - name: BuildApp
        run: npm run build
      - name: runTest
        run: npm test
